import resources_rc
from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_MainWindowContacts(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.setFixedSize(1367, 950)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setStyleSheet("* {\n"
                                         "    \n"
                                         "}\n"
                                         "\n"
                                         "\n"
                                         "#centralwidget{\n"
                                         "    background-color: #15202B;\n"
                                         "}\n"
                                         "\n"
                                         "#titleBar {\n"
                                         "    background-color: #242526;\n"
                                         "}\n"
                                         "\n"
                                         "#close, #restore, #minimize {\n"
                                         "    border-radius: 7px\n"
                                         "}\n"
                                         "#close {\n"
                                         "    background-color: red;\n"
                                         "}\n"
                                         "#restore {\n"
                                         "    background-color: yellow;\n"
                                         "}\n"
                                         "#minimize {\n"
                                         "    background-color: green;\n"
                                         "}\n"
                                         "\n"
                                         "#appName {\n"
                                         "    letter-spacing: 1.5px;\n"
                                         "    color: white;\n"
                                         "}\n"
                                         "\n"
                                         "#sideBar{\n"
                                         "    background-color: #192734;\n"
                                         "}\n"
                                         "#profile{\n"
                                         "    border-radius: 10px;\n"
                                         "}\n"
                                         "\n"
                                         "#chatTitle {\n"
                                         "    color: #fff;\n"
                                         "    margin-bottom: 40px\n"
                                         "}\n"
                                         "#search {\n"
                                         "    border: none;\n"
                                         "    border-bottom: 2px solid #404040;\n"
                                         "}\n"
                                         "#searchLineEdit {\n"
                                         "    background-color: transparent;\n"
                                         "    color: #fff\n"
                                         "}\n"
                                         "\n"
                                         "#chat1, #chat2, #chat3, #chat4, #chat5, #chat6, #chat7 {\n"
                                         "    background-color: #22303C;\n"
                                         "    border-radius: 10px;\n"
                                         "}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout =  QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleBar =  QFrame(self.centralwidget)
        font =  QFont()
        font.setPointSize(3)
        self.titleBar.setFont(font)
        self.titleBar.setFrameShape( QFrame.StyledPanel)
        self.titleBar.setFrameShadow( QFrame.Raised)
        self.titleBar.setObjectName("titleBar")
        self.horizontalLayout =  QHBoxLayout(self.titleBar)
        self.horizontalLayout.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainWindowTitle =  QFrame(self.titleBar)
        sizePolicy =  QSizePolicy(
             QSizePolicy.Expanding,  QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.mainWindowTitle.sizePolicy().hasHeightForWidth())
        self.mainWindowTitle.setSizePolicy(sizePolicy)
        self.mainWindowTitle.setFrameShape( QFrame.StyledPanel)
        self.mainWindowTitle.setFrameShadow( QFrame.Raised)
        self.mainWindowTitle.setObjectName("mainWindowTitle")
        self.verticalLayout_2 =  QVBoxLayout(self.mainWindowTitle)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(7)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.appName =  QLabel(self.mainWindowTitle)
        font =  QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.appName.setFont(font)
        self.appName.setStyleSheet("")
        self.appName.setObjectName("appName")
        self.verticalLayout_2.addWidget(
            self.appName, 0,  Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.mainWindowTitle)
        self.controls =  QFrame(self.titleBar)
        self.controls.setFrameShape( QFrame.StyledPanel)
        self.controls.setFrameShadow( QFrame.Raised)
        self.controls.setObjectName("controls")
        self.horizontalLayout_2 =  QHBoxLayout(self.controls)
        self.horizontalLayout_2.setContentsMargins(0, 0, 10, 0)
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.minimize =  QPushButton(self.controls)
        self.minimize.setMinimumSize( QSize(14, 14))
        self.minimize.setMaximumSize( QSize(14, 14))
        self.minimize.setText("")
        self.minimize.setObjectName("minimize")
        self.horizontalLayout_2.addWidget(self.minimize)
        self.restore =  QPushButton(self.controls)
        self.restore.setMinimumSize( QSize(14, 14))
        self.restore.setMaximumSize( QSize(14, 14))
        self.restore.setText("")
        self.restore.setObjectName("restore")
        self.horizontalLayout_2.addWidget(self.restore)
        self.close =  QPushButton(self.controls)
        self.close.setMinimumSize( QSize(14, 14))
        self.close.setMaximumSize( QSize(14, 14))
        self.close.setText("")
        self.close.setIconSize( QSize(20, 20))
        self.close.setObjectName("close")
        self.horizontalLayout_2.addWidget(self.close)
        self.horizontalLayout.addWidget(self.controls, 0,  Qt.AlignRight)
        self.verticalLayout.addWidget(self.titleBar)
        self.mainBody =  QWidget(self.centralwidget)
        sizePolicy =  QSizePolicy(
             QSizePolicy.Preferred,  QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.mainBody.sizePolicy().hasHeightForWidth())
        self.mainBody.setSizePolicy(sizePolicy)
        font =  QFont()
        font.setPointSize(8)
        self.mainBody.setFont(font)
        self.mainBody.setToolTip("")
        self.mainBody.setObjectName("mainBody")
        self.horizontalLayout_3 =  QHBoxLayout(self.mainBody)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sideBar =  QFrame(self.mainBody)
        self.sideBar.setMinimumSize( QSize(70, 0))
        self.sideBar.setMaximumSize( QSize(70, 16777215))
        self.sideBar.setFrameShape( QFrame.StyledPanel)
        self.sideBar.setFrameShadow( QFrame.Raised)
        self.sideBar.setObjectName("sideBar")
        self.verticalLayout_4 =  QVBoxLayout(self.sideBar)
        self.verticalLayout_4.setContentsMargins(0, 20, 0, 35)
        self.verticalLayout_4.setSpacing(30)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.appIcon =  QLabel(self.sideBar)
        self.appIcon.setMinimumSize( QSize(40, 40))
        self.appIcon.setMaximumSize( QSize(40, 40))
        self.appIcon.setText("")
        self.appIcon.setPixmap( QPixmap(":/appIcon/telegram.png"))
        self.appIcon.setScaledContents(True)
        self.appIcon.setObjectName("appIcon")
        self.verticalLayout_4.addWidget(
            self.appIcon, 0,  Qt.AlignHCenter |  Qt.AlignTop)
        self.Features =  QFrame(self.sideBar)
        self.Features.setFrameShape( QFrame.StyledPanel)
        self.Features.setFrameShadow( QFrame.Raised)
        self.Features.setObjectName("Features")
        self.verticalLayout_5 =  QVBoxLayout(self.Features)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 25)
        self.verticalLayout_5.setSpacing(30)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Profile =  QPushButton(self.Features)
        self.Profile.setText("")
        icon =  QIcon()
        icon.addPixmap( QPixmap(
            ":/appIcon/home-icon-silhouette.png"),  QIcon.Normal,  QIcon.Off)
        self.Profile.setIcon(icon)
        self.Profile.setIconSize( QSize(30, 30))
        self.Profile.setFlat(True)
        self.Profile.setObjectName("Profile")
        self.verticalLayout_5.addWidget(self.Profile)
        self.messages =  QPushButton(self.Features)
        self.messages.setMinimumSize( QSize(0, 0))
        self.messages.setText("")
        icon1 =  QIcon()
        icon1.addPixmap( QPixmap(":/appIcon/chat-2-512.png"),
                         QIcon.Normal,  QIcon.Off)
        self.messages.setIcon(icon1)
        self.messages.setIconSize( QSize(30, 30))
        self.messages.setFlat(True)
        self.messages.setObjectName("messages")
        self.verticalLayout_5.addWidget(self.messages)
        self.contacts =  QPushButton(self.Features)
        self.contacts.setText("")
        icon2 =  QIcon()
        icon2.addPixmap( QPixmap(":/appIcon/contacts-512.png"),
                         QIcon.Normal,  QIcon.Off)
        self.contacts.setIcon(icon2)
        self.contacts.setIconSize( QSize(30, 30))
        self.contacts.setFlat(True)
        self.contacts.setObjectName("contacts")
        self.verticalLayout_5.addWidget(self.contacts)
        self.settings =  QPushButton(self.Features)
        self.settings.setText("")
        icon3 =  QIcon()
        icon3.addPixmap( QPixmap(":/appIcon/settings (2).png"),
                         QIcon.Normal,  QIcon.Off)
        self.settings.setIcon(icon3)
        self.settings.setIconSize( QSize(30, 30))
        self.settings.setFlat(True)
        self.settings.setObjectName("settings")
        self.verticalLayout_5.addWidget(self.settings)
        self.mode =  QPushButton(self.Features)
        self.mode.setText("")
        icon4 =  QIcon()
        icon4.addPixmap( QPixmap(":/appIcon/night-mode (4).png"),
                         QIcon.Normal,  QIcon.Off)
        self.mode.setIcon(icon4)
        self.mode.setIconSize( QSize(30, 30))
        self.mode.setFlat(True)
        self.mode.setObjectName("mode")
        self.verticalLayout_5.addWidget(self.mode)
        self.verticalLayout_4.addWidget(self.Features)
        self.Ref_out =  QFrame(self.sideBar)
        self.Ref_out.setFrameShape( QFrame.StyledPanel)
        self.Ref_out.setFrameShadow( QFrame.Raised)
        self.Ref_out.setObjectName("Ref_out")
        self.verticalLayout_6 =  QVBoxLayout(self.Ref_out)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(30)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.refresh =  QPushButton(self.Ref_out)
        self.refresh.setText("")
        icon5 =  QIcon()
        icon5.addPixmap( QPixmap(":/appIcon/refresh-512.png"),
                         QIcon.Normal,  QIcon.Off)
        self.refresh.setIcon(icon5)
        self.refresh.setIconSize( QSize(30, 30))
        self.refresh.setFlat(True)
        self.refresh.setObjectName("refresh")
        self.verticalLayout_6.addWidget(self.refresh)
        self.logout =  QPushButton(self.Ref_out)
        self.logout.setText("")
        icon6 =  QIcon()
        icon6.addPixmap( QPixmap(":/appIcon/logout-512.png"),
                         QIcon.Normal,  QIcon.Off)
        self.logout.setIcon(icon6)
        self.logout.setIconSize( QSize(30, 30))
        self.logout.setFlat(True)
        self.logout.setObjectName("logout")
        self.verticalLayout_6.addWidget(self.logout)
        self.verticalLayout_4.addWidget(self.Ref_out, 0,  Qt.AlignBottom)
        self.horizontalLayout_3.addWidget(self.sideBar)
        self.Body =  QFrame(self.mainBody)
        font =  QFont()
        font.setPointSize(1)
        self.Body.setFont(font)
        self.Body.setFrameShape( QFrame.StyledPanel)
        self.Body.setFrameShadow( QFrame.Raised)
        self.Body.setObjectName("Body")
        self.name =  QLabel(self.Body)
        self.name.setGeometry( QRect(530, 70, 281, 71))
        palette =  QPalette()
        brush =  QBrush( QColor(255, 255, 255))
        brush.setStyle( Qt.SolidPattern)
        palette.setBrush( QPalette.Active,
                          QPalette.WindowText, brush)
        brush =  QBrush( QColor(255, 255, 255))
        brush.setStyle( Qt.SolidPattern)
        palette.setBrush( QPalette.Inactive,
                          QPalette.WindowText, brush)
        brush =  QBrush( QColor(120, 120, 120))
        brush.setStyle( Qt.SolidPattern)
        palette.setBrush( QPalette.Disabled,
                          QPalette.WindowText, brush)
        self.name.setPalette(palette)
        font =  QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(26)
        font.setBold(False)
        font.setWeight(50)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.icon =  QLabel(self.Body)
        self.icon.setGeometry( QRect(470, 80, 50, 50))
        self.icon.setMaximumSize( QSize(50, 50))
        font =  QFont()
        font.setPointSize(5)
        self.icon.setFont(font)
        self.icon.setText("")
        self.icon.setPixmap( QPixmap("user-add.png"))
        self.icon.setScaledContents(True)
        self.icon.setObjectName("icon")
        self.frame =  QFrame(self.Body)
        self.frame.setGeometry( QRect(300, 190, 701, 691))
        font =  QFont()
        font.setPointSize(12)
        self.frame.setFont(font)
        self.frame.setFrameShape( QFrame.StyledPanel)
        self.frame.setFrameShadow( QFrame.Raised)
        self.frame.setObjectName("frame")
        self.NameLabel =  QLabel(self.frame)
        self.NameLabel.setGeometry( QRect(80, 160, 396, 23))
        palette =  QPalette()
        brush =  QBrush( QColor(255, 255, 255))
        brush.setStyle( Qt.SolidPattern)
        palette.setBrush( QPalette.Active,
                          QPalette.WindowText, brush)
        brush =  QBrush( QColor(255, 255, 255))
        brush.setStyle( Qt.SolidPattern)
        palette.setBrush( QPalette.Inactive,
                          QPalette.WindowText, brush)
        brush =  QBrush( QColor(120, 120, 120))
        brush.setStyle( Qt.SolidPattern)
        palette.setBrush( QPalette.Disabled,
                          QPalette.WindowText, brush)
        self.NameLabel.setPalette(palette)
        font =  QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(10)
        self.NameLabel.setFont(font)
        self.NameLabel.setObjectName("NameLabel")
        self.contactName =  QLineEdit(self.frame)
        self.contactName.setGeometry( QRect(80, 180, 541, 49))
        self.contactName.setMinimumSize( QSize(0, 0))
        self.contactName.setMaximumSize( QSize(16777215, 16777215))
        font =  QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.contactName.setFont(font)
        self.contactName.setStyleSheet("letter-spacing: 1.5px;\n"
                                       "border: none;\n"
                                       "border-bottom: 1px solid lightgrey;\n"
                                       "background: transparent;\n"
                                       "color: white;\n"
                                       "padding: 5px;")
        self.contactName.setObjectName("contactName")
        self.contactPhone =  QLineEdit(self.frame)
        self.contactPhone.setGeometry( QRect(85, 330, 531, 49))
        self.contactPhone.setMinimumSize( QSize(0, 0))
        self.contactPhone.setMaximumSize( QSize(16777215, 16777215))
        font =  QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.contactPhone.setFont(font)
        self.contactPhone.setStyleSheet("letter-spacing: 1.5px;\n"
                                        "border: none;\n"
                                        "border-bottom: 1px solid lightgrey;\n"
                                        "background: transparent;\n"
                                        "color: white;\n"
                                        "padding: 5px;")
        self.contactPhone.setObjectName("contactPhone")
        self.PhoneLabel =  QLabel(self.frame)
        self.PhoneLabel.setGeometry( QRect(85, 310, 461, 23))
        palette =  QPalette()
        brush =  QBrush( QColor(255, 255, 255))
        brush.setStyle( Qt.SolidPattern)
        palette.setBrush( QPalette.Active,
                          QPalette.WindowText, brush)
        brush =  QBrush( QColor(255, 255, 255))
        brush.setStyle( Qt.SolidPattern)
        palette.setBrush( QPalette.Inactive,
                          QPalette.WindowText, brush)
        brush =  QBrush( QColor(120, 120, 120))
        brush.setStyle( Qt.SolidPattern)
        palette.setBrush( QPalette.Disabled,
                          QPalette.WindowText, brush)
        self.PhoneLabel.setPalette(palette)
        font =  QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(10)
        self.PhoneLabel.setFont(font)
        self.PhoneLabel.setObjectName("PhoneLabel")
        self.addButton =  QPushButton(self.frame)
        self.addButton.setGeometry( QRect(160, 490, 401, 41))
        palette =  QPalette()
        brush =  QBrush( QColor(255, 255, 255))
        brush.setStyle( Qt.SolidPattern)
        palette.setBrush( QPalette.Active,
                          QPalette.WindowText, brush)
        brush =  QBrush( QColor(0, 106, 255))
        brush.setStyle( Qt.SolidPattern)
        palette.setBrush( QPalette.Active,  QPalette.Button, brush)
        brush =  QBrush( QColor(255, 255, 255))
        brush.setStyle( Qt.SolidPattern)
        palette.setBrush( QPalette.Active,  QPalette.Text, brush)
        brush =  QBrush( QColor(255, 255, 255))
        brush.setStyle( Qt.SolidPattern)
        palette.setBrush( QPalette.Active,
                          QPalette.ButtonText, brush)
        brush =  QBrush( QColor(0, 106, 255))
        brush.setStyle( Qt.SolidPattern)
        palette.setBrush( QPalette.Active,  QPalette.Base, brush)
        brush =  QBrush( QColor(0, 106, 255))
        brush.setStyle( Qt.SolidPattern)
        palette.setBrush( QPalette.Active,  QPalette.Window, brush)
        brush =  QBrush( QColor(255, 255, 255, 128))
        brush.setStyle( Qt.NoBrush)
        palette.setBrush( QPalette.Active,
                          QPalette.PlaceholderText, brush)
        brush =  QBrush( QColor(255, 255, 255))
        brush.setStyle( Qt.SolidPattern)
        palette.setBrush( QPalette.Inactive,
                          QPalette.WindowText, brush)
        brush =  QBrush( QColor(0, 106, 255))
        brush.setStyle( Qt.SolidPattern)
        palette.setBrush( QPalette.Inactive,  QPalette.Button, brush)
        brush =  QBrush( QColor(255, 255, 255))
        brush.setStyle( Qt.SolidPattern)
        palette.setBrush( QPalette.Inactive,  QPalette.Text, brush)
        brush =  QBrush( QColor(255, 255, 255))
        brush.setStyle( Qt.SolidPattern)
        palette.setBrush( QPalette.Inactive,
                          QPalette.ButtonText, brush)
        brush =  QBrush( QColor(0, 106, 255))
        brush.setStyle( Qt.SolidPattern)
        palette.setBrush( QPalette.Inactive,  QPalette.Base, brush)
        brush =  QBrush( QColor(0, 106, 255))
        brush.setStyle( Qt.SolidPattern)
        palette.setBrush( QPalette.Inactive,  QPalette.Window, brush)
        brush =  QBrush( QColor(255, 255, 255, 128))
        brush.setStyle( Qt.NoBrush)
        palette.setBrush( QPalette.Inactive,
                          QPalette.PlaceholderText, brush)
        brush =  QBrush( QColor(255, 255, 255))
        brush.setStyle( Qt.SolidPattern)
        palette.setBrush( QPalette.Disabled,
                          QPalette.WindowText, brush)
        brush =  QBrush( QColor(0, 106, 255))
        brush.setStyle( Qt.SolidPattern)
        palette.setBrush( QPalette.Disabled,  QPalette.Button, brush)
        brush =  QBrush( QColor(255, 255, 255))
        brush.setStyle( Qt.SolidPattern)
        palette.setBrush( QPalette.Disabled,  QPalette.Text, brush)
        brush =  QBrush( QColor(255, 255, 255))
        brush.setStyle( Qt.SolidPattern)
        palette.setBrush( QPalette.Disabled,
                          QPalette.ButtonText, brush)
        brush =  QBrush( QColor(0, 106, 255))
        brush.setStyle( Qt.SolidPattern)
        palette.setBrush( QPalette.Disabled,  QPalette.Base, brush)
        brush =  QBrush( QColor(0, 106, 255))
        brush.setStyle( Qt.SolidPattern)
        palette.setBrush( QPalette.Disabled,  QPalette.Window, brush)
        brush =  QBrush( QColor(255, 255, 255, 128))
        brush.setStyle( Qt.NoBrush)
        palette.setBrush( QPalette.Disabled,QPalette.PlaceholderText, brush)
        self.addButton.setPalette(palette)
        font =  QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(14)
        self.addButton.setFont(font)
        self.addButton.setStyleSheet("border-radius: 7px; background-color: #006aff;color: white;")
        self.addButton.setObjectName("addButton")
        self.addButton.shortcut = QShortcut(QKeySequence("Return"), self.addButton)
        self.toUserFromPhoneFrame = QLabel(self.frame)
        self.toUserFromPhoneFrame.setGeometry(QRect(80, 380, 396, 51))
        palette = QPalette()
        brush = QBrush(QColor(0, 106, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush = QBrush(QColor(0, 106, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.Text, brush)
        brush = QBrush(QColor(0, 106, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.ButtonText, brush)
        brush = QBrush(QColor(0, 106, 255, 128))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.PlaceholderText, brush)
        brush = QBrush(QColor(0, 106, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        brush = QBrush(QColor(0, 106, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.Text, brush)
        brush = QBrush(QColor(0, 106, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.ButtonText, brush)
        brush = QBrush(QColor(0, 106, 255, 128))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.PlaceholderText, brush)
        brush = QBrush(QColor(120, 120, 120))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        brush = QBrush(QColor(120, 120, 120))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.Text, brush)
        brush = QBrush(QColor(120, 120, 120))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.ButtonText, brush)
        brush = QBrush(QColor(0, 0, 0, 128))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.PlaceholderText, brush)
        self.toUserFromPhoneFrame.setPalette(palette)
        font = QFont()
        font.setFamily("Trebuchet MS")
        font.setPointSize(9)
        self.toUserFromPhoneFrame.setFont(font)
        self.toUserFromPhoneFrame.setText("")
        self.toUserFromPhoneFrame.setObjectName("toUserFromPhoneFrame")
        self.doneMessage = QLabel(self.frame)
        self.doneMessage.setGeometry(QRect(140, 560, 451, 41))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        brush = QBrush(QColor(120, 120, 120))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush)
        self.doneMessage.setPalette(palette)
        font = QFont()
        font.setFamily("Verdana")
        font.setPointSize(13)
        self.doneMessage.setFont(font)
        self.doneMessage.setText("")
        self.doneMessage.setAlignment(Qt.AlignCenter)
        self.doneMessage.setObjectName("doneMessage")
        self.horizontalLayout_3.addWidget(self.Body)
        self.verticalLayout.addWidget(self.mainBody)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QMetaObject.connectSlotsByName(MainWindow)
        self.horizontalLayout_3.addWidget(self.Body)
        self.verticalLayout.addWidget(self.mainBody)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate =  QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.appName.setToolTip(_translate("MainWindow", "App Name"))
        self.appName.setText(_translate("MainWindow", "Chat Zone"))
        self.minimize.setToolTip(_translate("MainWindow", "Minimize"))
        self.restore.setToolTip(_translate("MainWindow", "Restore"))
        self.close.setToolTip(_translate("MainWindow", "Close"))
        self.appIcon.setToolTip(_translate("MainWindow", "Chat Zone"))
        self.Profile.setToolTip(_translate("MainWindow", "Profile"))
        self.messages.setToolTip(_translate("MainWindow", "Messages"))
        self.contacts.setToolTip(_translate("MainWindow", "Contacts"))
        self.settings.setToolTip(_translate("MainWindow", "Settings"))
        self.mode.setToolTip(_translate("MainWindow", "Light Mode"))
        self.refresh.setToolTip(_translate("MainWindow", "Refresh"))
        self.logout.setToolTip(_translate("MainWindow", "Logout"))
        self.name.setText(_translate("MainWindow", "New Contact"))
        self.NameLabel.setText(_translate("MainWindow", "User Name"))
        self.PhoneLabel.setText(_translate("MainWindow", "Phone Number"))
        self.addButton.setText(_translate("MainWindow", "Add contact"))

