import resources_rc
from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *

class Ui_MainWindowsettings(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setFixedSize(1367, 950)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setStyleSheet("* {\n"
                                         "    \n"
                                         "}\n"
                                         "\n"
                                         "\n"
                                         "#centralwidget{\n"
                                         "    background-color: #15202B;\n"
                                         "}\n"
                                         "\n"
                                         "#titleBar {\n"
                                         "    background-color: #242526;\n"
                                         "}\n"
                                         "\n"
                                         "#close, #restore, #minimize {\n"
                                         "    border-radius: 7px\n"
                                         "}\n"
                                         "#close {\n"
                                         "    background-color: red;\n"
                                         "}\n"
                                         "#restore {\n"
                                         "    background-color: yellow;\n"
                                         "}\n"
                                         "#minimize {\n"
                                         "    background-color: green;\n"
                                         "}\n"
                                         "\n"
                                         "#appName {\n"
                                         "    letter-spacing: 1.5px;\n"
                                         "    color: white;\n"
                                         "}\n"
                                         "\n"
                                         "#sideBar{\n"
                                         "    background-color: #192734;\n"
                                         "}\n"
                                         "#profile{\n"
                                         "    border-radius: 10px;\n"
                                         "}\n"
                                         "\n"
                                         "#chatTitle {\n"
                                         "    color: #fff;\n"
                                         "    margin-bottom: 40px\n"
                                         "}\n"
                                         "#search {\n"
                                         "    border: none;\n"
                                         "    border-bottom: 2px solid #404040;\n"
                                         "}\n"
                                         "#searchLineEdit {\n"
                                         "    background-color: transparent;\n"
                                         "    color: #fff\n"
                                         "}\n"
                                         "\n"
                                         "#chat1, #chat2, #chat3, #chat4, #chat5, #chat6, #chat7 {\n"
                                         "    background-color: #22303C;\n"
                                         "    border-radius: 10px;\n"
                                         "}")
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleBar = QFrame(self.centralwidget)
        font = QFont()
        font.setPointSize(3)
        self.titleBar.setFont(font)
        self.titleBar.setFrameShape(QFrame.StyledPanel)
        self.titleBar.setFrameShadow(QFrame.Raised)
        self.titleBar.setObjectName("titleBar")
        self.horizontalLayout = QHBoxLayout(self.titleBar)
        self.horizontalLayout.setContentsMargins(0, 5, 0, 5)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.mainWindowTitle = QFrame(self.titleBar)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding,  QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.mainWindowTitle.sizePolicy().hasHeightForWidth())
        self.mainWindowTitle.setSizePolicy(sizePolicy)
        self.mainWindowTitle.setFrameShape(QFrame.StyledPanel)
        self.mainWindowTitle.setFrameShadow(QFrame.Raised)
        self.mainWindowTitle.setObjectName("mainWindowTitle")
        self.verticalLayout_2 = QVBoxLayout(self.mainWindowTitle)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(7)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.appName = QLabel(self.mainWindowTitle)
        font = QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.appName.setFont(font)
        self.appName.setStyleSheet("")
        self.appName.setObjectName("appName")
        self.verticalLayout_2.addWidget(self.appName, 0,  Qt.AlignHCenter)
        self.horizontalLayout.addWidget(self.mainWindowTitle)
        self.controls = QFrame(self.titleBar)
        self.controls.setFrameShape(QFrame.StyledPanel)
        self.controls.setFrameShadow(QFrame.Raised)
        self.controls.setObjectName("controls")
        self.horizontalLayout_2 = QHBoxLayout(self.controls)
        self.horizontalLayout_2.setContentsMargins(0, 0, 10, 0)
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.minimize = QPushButton(self.controls)
        self.minimize.setMinimumSize(QSize(14, 14))
        self.minimize.setMaximumSize(QSize(14, 14))
        self.minimize.setText("")
        self.minimize.setObjectName("minimize")
        self.horizontalLayout_2.addWidget(self.minimize)
        self.restore = QPushButton(self.controls)
        self.restore.setMinimumSize(QSize(14, 14))
        self.restore.setMaximumSize(QSize(14, 14))
        self.restore.setText("")
        self.restore.setObjectName("restore")
        self.horizontalLayout_2.addWidget(self.restore)
        self.close = QPushButton(self.controls)
        self.close.setMinimumSize(QSize(14, 14))
        self.close.setMaximumSize(QSize(14, 14))
        self.close.setText("")
        self.close.setIconSize(QSize(20, 20))
        self.close.setObjectName("close")
        self.horizontalLayout_2.addWidget(self.close)
        self.horizontalLayout.addWidget(self.controls, 0,  Qt.AlignRight)
        self.verticalLayout.addWidget(self.titleBar)
        self.mainBody = QWidget(self.centralwidget)
        sizePolicy = QSizePolicy(QSizePolicy.Preferred,  QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(
            self.mainBody.sizePolicy().hasHeightForWidth())
        self.mainBody.setSizePolicy(sizePolicy)
        font = QFont()
        font.setPointSize(8)
        self.mainBody.setFont(font)
        self.mainBody.setToolTip("")
        self.mainBody.setObjectName("mainBody")
        self.horizontalLayout_3 = QHBoxLayout(self.mainBody)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.sideBar = QFrame(self.mainBody)
        self.sideBar.setMinimumSize(QSize(70, 0))
        self.sideBar.setMaximumSize(QSize(70, 16777215))
        self.sideBar.setFrameShape(QFrame.StyledPanel)
        self.sideBar.setFrameShadow(QFrame.Raised)
        self.sideBar.setObjectName("sideBar")
        self.verticalLayout_4 = QVBoxLayout(self.sideBar)
        self.verticalLayout_4.setContentsMargins(0, 20, 0, 35)
        self.verticalLayout_4.setSpacing(30)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.appIcon = QLabel(self.sideBar)
        self.appIcon.setMinimumSize(QSize(40, 40))
        self.appIcon.setMaximumSize(QSize(40, 40))
        self.appIcon.setText("")
        self.appIcon.setPixmap(QPixmap(":/appIcon/telegram.png"))
        self.appIcon.setScaledContents(True)
        self.appIcon.setObjectName("appIcon")
        self.verticalLayout_4.addWidget(
            self.appIcon, 0,  Qt.AlignHCenter | Qt.AlignTop)
        self.Features = QFrame(self.sideBar)
        self.Features.setFrameShape(QFrame.StyledPanel)
        self.Features.setFrameShadow(QFrame.Raised)
        self.Features.setObjectName("Features")
        self.verticalLayout_5 = QVBoxLayout(self.Features)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 25)
        self.verticalLayout_5.setSpacing(30)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Profile = QPushButton(self.Features)
        self.Profile.setText("")
        icon = QIcon()
        icon.addPixmap(QPixmap(":/appIcon/home-icon-silhouette.png"),
                       QIcon.Normal,  QIcon.Off)
        self.Profile.setIcon(icon)
        self.Profile.setIconSize(QSize(30, 30))
        self.Profile.setFlat(True)
        self.Profile.setObjectName("Profile")
        self.verticalLayout_5.addWidget(self.Profile)
        self.messages = QPushButton(self.Features)
        self.messages.setMinimumSize(QSize(0, 0))
        self.messages.setText("")
        icon1 = QIcon()
        icon1.addPixmap(QPixmap(":/appIcon/chat-2-512.png"),
                        QIcon.Normal,  QIcon.Off)
        self.messages.setIcon(icon1)
        self.messages.setIconSize(QSize(30, 30))
        self.messages.setFlat(True)
        self.messages.setObjectName("messages")
        self.verticalLayout_5.addWidget(self.messages)
        self.contacts = QPushButton(self.Features)
        self.contacts.setText("")
        icon2 = QIcon()
        icon2.addPixmap(QPixmap(":/appIcon/contacts-512.png"),
                        QIcon.Normal,  QIcon.Off)
        self.contacts.setIcon(icon2)
        self.contacts.setIconSize(QSize(30, 30))
        self.contacts.setFlat(True)
        self.contacts.setObjectName("contacts")
        self.verticalLayout_5.addWidget(self.contacts)
        self.settings = QPushButton(self.Features)
        self.settings.setText("")
        icon3 = QIcon()
        icon3.addPixmap(QPixmap(":/appIcon/settings (2).png"),
                        QIcon.Normal,  QIcon.Off)
        self.settings.setIcon(icon3)
        self.settings.setIconSize(QSize(30, 30))
        self.settings.setFlat(True)
        self.settings.setObjectName("settings")
        self.verticalLayout_5.addWidget(self.settings)
        self.mode = QPushButton(self.Features)
        self.mode.setText("")
        icon4 = QIcon()
        icon4.addPixmap(QPixmap(":/appIcon/night-mode (4).png"),
                        QIcon.Normal,  QIcon.Off)
        self.mode.setIcon(icon4)
        self.mode.setIconSize(QSize(30, 30))
        self.mode.setFlat(True)
        self.mode.setObjectName("mode")
        self.verticalLayout_5.addWidget(self.mode)
        self.verticalLayout_4.addWidget(self.Features)
        self.Ref_out = QFrame(self.sideBar)
        self.Ref_out.setFrameShape(QFrame.StyledPanel)
        self.Ref_out.setFrameShadow(QFrame.Raised)
        self.Ref_out.setObjectName("Ref_out")
        self.verticalLayout_6 = QVBoxLayout(self.Ref_out)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(30)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.refresh = QPushButton(self.Ref_out)
        self.refresh.setText("")
        icon5 = QIcon()
        icon5.addPixmap(QPixmap(":/appIcon/refresh-512.png"),
                        QIcon.Normal,  QIcon.Off)
        self.refresh.setIcon(icon5)
        self.refresh.setIconSize(QSize(30, 30))
        self.refresh.setFlat(True)
        self.refresh.setObjectName("refresh")
        self.verticalLayout_6.addWidget(self.refresh)
        self.logout = QPushButton(self.Ref_out)
        self.logout.setText("")
        icon6 = QIcon()
        icon6.addPixmap(QPixmap(":/appIcon/logout-512.png"),
                        QIcon.Normal,  QIcon.Off)
        self.logout.setIcon(icon6)
        self.logout.setIconSize(QSize(30, 30))
        self.logout.setFlat(True)
        self.logout.setObjectName("logout")
        self.verticalLayout_6.addWidget(self.logout)
        self.verticalLayout_4.addWidget(self.Ref_out, 0,  Qt.AlignBottom)
        self.horizontalLayout_3.addWidget(self.sideBar)
        self.Body = QFrame(self.mainBody)
        font = QFont()
        font.setPointSize(1)
        self.Body.setFont(font)
        self.Body.setFrameShape(QFrame.StyledPanel)
        self.Body.setFrameShadow(QFrame.Raised)
        self.Body.setObjectName("Body")
        self.editUserInfo = QFrame(self.Body)
        self.editUserInfo.setGeometry(QRect(570, 50, 691, 841))
        self.editUserInfo.setFrameShape(QFrame.StyledPanel)
        self.editUserInfo.setFrameShadow(QFrame.Raised)
        self.editUserInfo.setObjectName("editUserInfo")
        self.UN = QFrame(self.editUserInfo)
        self.UN.setGeometry(QRect(10, 40, 757, 81))
        self.UN.setFrameShape(QFrame.StyledPanel)
        self.UN.setFrameShadow(QFrame.Raised)
        self.UN.setObjectName("UN")
        self.usernameLabel = QLabel(self.UN)
        self.usernameLabel.setGeometry(QRect(0, 0, 391, 31))
        palette = QPalette()
        brush = QBrush(QColor(214, 214, 214))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.WindowText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.ButtonText, brush)
        brush = QBrush(QColor(255, 255, 255, 128))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.PlaceholderText, brush)
        brush = QBrush(QColor(214, 214, 214))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.WindowText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.ButtonText, brush)
        brush = QBrush(QColor(255, 255, 255, 128))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.PlaceholderText, brush)
        brush = QBrush(QColor(120, 120, 120))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.WindowText, brush)
        brush = QBrush(QColor(120, 120, 120))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.Text, brush)
        brush = QBrush(QColor(120, 120, 120))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.ButtonText, brush)
        brush = QBrush(QColor(0, 0, 0, 128))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.PlaceholderText, brush)
        self.usernameLabel.setPalette(palette)
        font = QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.usernameLabel.setFont(font)
        self.usernameLabel.setStyleSheet("border-bottom: 1px solid white;")
        self.usernameLabel.setObjectName("usernameLabel")
        self.username = QLineEdit(self.UN)
        self.username.setGeometry(QRect(0, 40, 571, 41))
        self.username.setMinimumSize(QSize(0, 0))
        self.username.setMaximumSize(QSize(16777215, 16777215))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.WindowText, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.Button, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.ButtonText, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.Base, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.Window, brush)
        brush = QBrush(QColor(255, 255, 255, 128))
        brush.setStyle(Qt.NoBrush)
        palette.setBrush(QPalette.Active,  QPalette.PlaceholderText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.WindowText, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.Button, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.ButtonText, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.Base, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.Window, brush)
        brush = QBrush(QColor(255, 255, 255, 128))
        brush.setStyle(Qt.NoBrush)
        palette.setBrush(QPalette.Inactive,  QPalette.PlaceholderText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.WindowText, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.Button, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.ButtonText, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.Base, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.Window, brush)
        brush = QBrush(QColor(255, 255, 255, 128))
        brush.setStyle(Qt.NoBrush)
        palette.setBrush(QPalette.Disabled,  QPalette.PlaceholderText, brush)
        self.username.setPalette(palette)
        font = QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.username.setFont(font)
        self.username.setStyleSheet("font-size: 25px;\n"
                                    "letter-spacing: 1.5px;\n"
                                    "background: transparent;\n"
                                    "border:none;\n"
                                    "border-bottom: 1px solid grey;\n"
                                    "padding: 5px;\n"
                                    "color: white;")
        self.username.setClearButtonEnabled(True)
        self.username.setObjectName("username")
        self.editUserNameButton = QPushButton(self.UN)
        self.editUserNameButton.setGeometry(QRect(572, 37, 51, 41))
        self.editUserNameButton.setText("")
        icon7 = QIcon()
        icon7.addPixmap(QPixmap("pencil.png"),  QIcon.Normal,  QIcon.Off)
        self.editUserNameButton.setIcon(icon7)
        self.editUserNameButton.setIconSize(QSize(20, 20))
        self.editUserNameButton.setFlat(True)
        self.editUserNameButton.setObjectName("editUserNameButton")
        self.FN = QFrame(self.editUserInfo)
        self.FN.setGeometry(QRect(10, 170, 757, 81))
        self.FN.setStyleSheet("border-bottom: 1px solid white;")
        self.FN.setFrameShape(QFrame.StyledPanel)
        self.FN.setFrameShadow(QFrame.Raised)
        self.FN.setObjectName("FN")
        self.firstnameLabel = QLabel(self.FN)
        self.firstnameLabel.setGeometry(QRect(0, 0, 391, 31))
        palette = QPalette()
        brush = QBrush(QColor(214, 214, 214))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.WindowText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.ButtonText, brush)
        brush = QBrush(QColor(255, 255, 255, 128))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.PlaceholderText, brush)
        brush = QBrush(QColor(214, 214, 214))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.WindowText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.ButtonText, brush)
        brush = QBrush(QColor(255, 255, 255, 128))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.PlaceholderText, brush)
        brush = QBrush(QColor(120, 120, 120))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.WindowText, brush)
        brush = QBrush(QColor(120, 120, 120))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.Text, brush)
        brush = QBrush(QColor(120, 120, 120))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.ButtonText, brush)
        brush = QBrush(QColor(0, 0, 0, 128))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.PlaceholderText, brush)
        self.firstnameLabel.setPalette(palette)
        font = QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.firstnameLabel.setFont(font)
        self.firstnameLabel.setStyleSheet("border-bottom: 1px solid white;")
        self.firstnameLabel.setObjectName("firstnameLabel")
        self.firstName = QLineEdit(self.FN)
        self.firstName.setGeometry(QRect(0, 40, 571, 41))
        self.firstName.setMinimumSize(QSize(0, 0))
        self.firstName.setMaximumSize(QSize(16777215, 16777215))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.WindowText, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.Button, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.ButtonText, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.Base, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.Window, brush)
        brush = QBrush(QColor(255, 255, 255, 128))
        brush.setStyle(Qt.NoBrush)
        palette.setBrush(QPalette.Active,  QPalette.PlaceholderText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.WindowText, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.Button, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.ButtonText, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.Base, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.Window, brush)
        brush = QBrush(QColor(255, 255, 255, 128))
        brush.setStyle(Qt.NoBrush)
        palette.setBrush(QPalette.Inactive,  QPalette.PlaceholderText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.WindowText, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.Button, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.ButtonText, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.Base, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.Window, brush)
        brush = QBrush(QColor(255, 255, 255, 128))
        brush.setStyle(Qt.NoBrush)
        palette.setBrush(QPalette.Disabled,  QPalette.PlaceholderText, brush)
        self.firstName.setPalette(palette)
        font = QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.firstName.setFont(font)
        self.firstName.setStyleSheet("font-size: 25px;\n"
                                     "letter-spacing: 1.5px;\n"
                                     "background: transparent;\n"
                                     "border:none;\n"
                                     "border-bottom: 1px solid grey;\n"
                                     "padding: 5px;\n"
                                     "color: white;")
        self.firstName.setClearButtonEnabled(True)
        self.firstName.setObjectName("firstName")
        self.editFirstNameButton = QPushButton(self.FN)
        self.editFirstNameButton.setGeometry(QRect(570, 40, 51, 41))
        self.editFirstNameButton.setText("")
        self.editFirstNameButton.setIcon(icon7)
        self.editFirstNameButton.setIconSize(QSize(20, 20))
        self.editFirstNameButton.setFlat(True)
        self.editFirstNameButton.setObjectName("editFirstNameButton")
        self.LN = QFrame(self.editUserInfo)
        self.LN.setGeometry(QRect(10, 300, 757, 81))
        self.LN.setFrameShape(QFrame.StyledPanel)
        self.LN.setFrameShadow(QFrame.Raised)
        self.LN.setObjectName("LN")
        self.lastNameLabel = QLabel(self.LN)
        self.lastNameLabel.setGeometry(QRect(0, 0, 391, 31))
        palette = QPalette()
        brush = QBrush(QColor(214, 214, 214))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.WindowText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.ButtonText, brush)
        brush = QBrush(QColor(255, 255, 255, 128))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.PlaceholderText, brush)
        brush = QBrush(QColor(214, 214, 214))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.WindowText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.ButtonText, brush)
        brush = QBrush(QColor(255, 255, 255, 128))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.PlaceholderText, brush)
        brush = QBrush(QColor(120, 120, 120))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.WindowText, brush)
        brush = QBrush(QColor(120, 120, 120))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.Text, brush)
        brush = QBrush(QColor(120, 120, 120))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.ButtonText, brush)
        brush = QBrush(QColor(0, 0, 0, 128))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.PlaceholderText, brush)
        self.lastNameLabel.setPalette(palette)
        font = QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.lastNameLabel.setFont(font)
        self.lastNameLabel.setStyleSheet("border-bottom: 1px solid white;")
        self.lastNameLabel.setObjectName("lastNameLabel")
        self.Lastname = QLineEdit(self.LN)
        self.Lastname.setGeometry(QRect(0, 40, 571, 41))
        self.Lastname.setMinimumSize(QSize(0, 0))
        self.Lastname.setMaximumSize(QSize(16777215, 16777215))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.WindowText, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.Button, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.ButtonText, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.Base, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.Window, brush)
        brush = QBrush(QColor(255, 255, 255, 128))
        brush.setStyle(Qt.NoBrush)
        palette.setBrush(QPalette.Active,  QPalette.PlaceholderText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.WindowText, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.Button, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.ButtonText, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.Base, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.Window, brush)
        brush = QBrush(QColor(255, 255, 255, 128))
        brush.setStyle(Qt.NoBrush)
        palette.setBrush(QPalette.Inactive,  QPalette.PlaceholderText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.WindowText, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.Button, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.ButtonText, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.Base, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.Window, brush)
        brush = QBrush(QColor(255, 255, 255, 128))
        brush.setStyle(Qt.NoBrush)
        palette.setBrush(QPalette.Disabled,  QPalette.PlaceholderText, brush)
        self.Lastname.setPalette(palette)
        font = QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.Lastname.setFont(font)
        self.Lastname.setStyleSheet("font-size: 25px;\n"
                                    "letter-spacing: 1.5px;\n"
                                    "background: transparent;\n"
                                    "border:none;\n"
                                    "border-bottom: 1px solid grey;\n"
                                    "padding: 5px;\n"
                                    "color: white;")
        self.Lastname.setClearButtonEnabled(True)
        self.Lastname.setObjectName("Lastname")
        self.editLastNameButton = QPushButton(self.LN)
        self.editLastNameButton.setGeometry(QRect(570, 40, 51, 41))
        self.editLastNameButton.setText("")
        self.editLastNameButton.setIcon(icon7)
        self.editLastNameButton.setFlat(True)
        self.editLastNameButton.setObjectName("editLastNameButton")
        self.BIO = QFrame(self.editUserInfo)
        self.BIO.setGeometry(QRect(10, 580, 757, 81))
        self.BIO.setFrameShape(QFrame.StyledPanel)
        self.BIO.setFrameShadow(QFrame.Raised)
        self.BIO.setObjectName("BIO")
        self.bioLabel = QLabel(self.BIO)
        self.bioLabel.setGeometry(QRect(0, 0, 391, 31))
        palette = QPalette()
        brush = QBrush(QColor(214, 214, 214))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.WindowText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.ButtonText, brush)
        brush = QBrush(QColor(255, 255, 255, 128))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.PlaceholderText, brush)
        brush = QBrush(QColor(214, 214, 214))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.WindowText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.ButtonText, brush)
        brush = QBrush(QColor(255, 255, 255, 128))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.PlaceholderText, brush)
        brush = QBrush(QColor(120, 120, 120))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.WindowText, brush)
        brush = QBrush(QColor(120, 120, 120))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.Text, brush)
        brush = QBrush(QColor(120, 120, 120))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.ButtonText, brush)
        brush = QBrush(QColor(0, 0, 0, 128))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.PlaceholderText, brush)
        self.bioLabel.setPalette(palette)
        font = QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.bioLabel.setFont(font)
        self.bioLabel.setStyleSheet("border-bottom: 1px solid white;")
        self.bioLabel.setObjectName("bioLabel")
        self.bio = QLineEdit(self.BIO)
        self.bio.setGeometry(QRect(0, 30, 571, 51))
        self.bio.setMinimumSize(QSize(0, 0))
        self.bio.setMaximumSize(QSize(16777215, 16777215))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.WindowText, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.Button, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.ButtonText, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.Base, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.Window, brush)
        brush = QBrush(QColor(255, 255, 255, 128))
        brush.setStyle(Qt.NoBrush)
        palette.setBrush(QPalette.Active,  QPalette.PlaceholderText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.WindowText, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.Button, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.ButtonText, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.Base, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.Window, brush)
        brush = QBrush(QColor(255, 255, 255, 128))
        brush.setStyle(Qt.NoBrush)
        palette.setBrush(QPalette.Inactive,  QPalette.PlaceholderText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.WindowText, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.Button, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.ButtonText, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.Base, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.Window, brush)
        brush = QBrush(QColor(255, 255, 255, 128))
        brush.setStyle(Qt.NoBrush)
        palette.setBrush(QPalette.Disabled,  QPalette.PlaceholderText, brush)
        self.bio.setPalette(palette)
        font = QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.bio.setFont(font)
        self.bio.setStyleSheet("font-size: 25px;\n"
                               "letter-spacing: 1.5px;\n"
                               "background: transparent;\n"
                               "border:none;\n"
                               "border-bottom: 1px solid grey;\n"
                               "padding: 10px 15px;\n"
                               "color: white;")
        self.bio.setClearButtonEnabled(True)
        self.bio.setObjectName("bio")
        self.editBioButton = QPushButton(self.BIO)
        self.editBioButton.setGeometry(QRect(570, 40, 51, 41))
        self.editBioButton.setText("")
        self.editBioButton.setIcon(icon7)
        self.editBioButton.setFlat(True)
        self.editBioButton.setObjectName("editBioButton")
        self.PN = QFrame(self.editUserInfo)
        self.PN.setGeometry(QRect(10, 440, 757, 81))
        self.PN.setFrameShape(QFrame.StyledPanel)
        self.PN.setFrameShadow(QFrame.Raised)
        self.PN.setObjectName("PN")
        self.phoneNumber = QLineEdit(self.PN)
        self.phoneNumber.setGeometry(QRect(0, 40, 571, 41))
        self.phoneNumber.setMinimumSize(QSize(0, 0))
        self.phoneNumber.setMaximumSize(QSize(16777215, 16777215))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.WindowText, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.Button, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.ButtonText, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.Base, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.Window, brush)
        brush = QBrush(QColor(255, 255, 255, 128))
        brush.setStyle(Qt.NoBrush)
        palette.setBrush(QPalette.Active,  QPalette.PlaceholderText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.WindowText, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.Button, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.ButtonText, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.Base, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.Window, brush)
        brush = QBrush(QColor(255, 255, 255, 128))
        brush.setStyle(Qt.NoBrush)
        palette.setBrush(QPalette.Inactive,  QPalette.PlaceholderText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.WindowText, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.Button, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.ButtonText, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.Base, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.Window, brush)
        brush = QBrush(QColor(255, 255, 255, 128))
        brush.setStyle(Qt.NoBrush)
        palette.setBrush(QPalette.Disabled,  QPalette.PlaceholderText, brush)
        self.phoneNumber.setPalette(palette)
        font = QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.phoneNumber.setFont(font)
        self.phoneNumber.setStyleSheet("font-size: 25px;\n"
                                       "letter-spacing: 1.5px;\n"
                                       "background: transparent;\n"
                                       "border:none;\n"
                                       "border-bottom: 1px solid grey;\n"
                                       "padding: 10px;\n"
                                       "color: white;")
        self.phoneNumber.setClearButtonEnabled(True)
        self.phoneNumber.setObjectName("phoneNumber")
        self.phoneLabel = QLabel(self.PN)
        self.phoneLabel.setGeometry(QRect(0, 0, 391, 31))
        palette = QPalette()
        brush = QBrush(QColor(214, 214, 214))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.WindowText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.ButtonText, brush)
        brush = QBrush(QColor(255, 255, 255, 128))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.PlaceholderText, brush)
        brush = QBrush(QColor(214, 214, 214))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.WindowText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.ButtonText, brush)
        brush = QBrush(QColor(255, 255, 255, 128))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.PlaceholderText, brush)
        brush = QBrush(QColor(120, 120, 120))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.WindowText, brush)
        brush = QBrush(QColor(120, 120, 120))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.Text, brush)
        brush = QBrush(QColor(120, 120, 120))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.ButtonText, brush)
        brush = QBrush(QColor(0, 0, 0, 128))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.PlaceholderText, brush)
        self.phoneLabel.setPalette(palette)
        font = QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.phoneLabel.setFont(font)
        self.phoneLabel.setStyleSheet("border-bottom: 1px solid white;")
        self.phoneLabel.setObjectName("phoneLabel")
        self.editPhoneButton = QPushButton(self.PN)
        self.editPhoneButton.setGeometry(QRect(570, 40, 51, 41))
        self.editPhoneButton.setText("")
        self.editPhoneButton.setIcon(icon7)
        self.editPhoneButton.setFlat(True)
        self.editPhoneButton.setObjectName("editPhoneButton")
        self.Pass = QFrame(self.editUserInfo)
        self.Pass.setGeometry(QRect(10, 710, 757, 81))
        self.Pass.setFrameShape(QFrame.StyledPanel)
        self.Pass.setFrameShadow(QFrame.Raised)
        self.Pass.setObjectName("Pass")
        self.PasswordLabel = QLabel(self.Pass)
        self.PasswordLabel.setGeometry(QRect(0, 0, 391, 31))
        palette = QPalette()
        brush = QBrush(QColor(214, 214, 214))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.WindowText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.ButtonText, brush)
        brush = QBrush(QColor(255, 255, 255, 128))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.PlaceholderText, brush)
        brush = QBrush(QColor(214, 214, 214))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.WindowText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.ButtonText, brush)
        brush = QBrush(QColor(255, 255, 255, 128))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.PlaceholderText, brush)
        brush = QBrush(QColor(120, 120, 120))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.WindowText, brush)
        brush = QBrush(QColor(120, 120, 120))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.Text, brush)
        brush = QBrush(QColor(120, 120, 120))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.ButtonText, brush)
        brush = QBrush(QColor(0, 0, 0, 128))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.PlaceholderText, brush)
        self.PasswordLabel.setPalette(palette)
        font = QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.PasswordLabel.setFont(font)
        self.PasswordLabel.setStyleSheet("border-bottom: 1px solid white;")
        self.PasswordLabel.setObjectName("PasswordLabel")
        self.password = QLineEdit(self.Pass)
        self.password.setGeometry(QRect(0, 40, 571, 41))
        self.password.setMinimumSize(QSize(0, 0))
        self.password.setMaximumSize(QSize(16777215, 16777215))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.WindowText, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.Button, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.ButtonText, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.Base, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.Window, brush)
        brush = QBrush(QColor(255, 255, 255, 128))
        brush.setStyle(Qt.NoBrush)
        palette.setBrush(QPalette.Active,  QPalette.PlaceholderText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.WindowText, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.Button, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.ButtonText, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.Base, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.Window, brush)
        brush = QBrush(QColor(255, 255, 255, 128))
        brush.setStyle(Qt.NoBrush)
        palette.setBrush(QPalette.Inactive,  QPalette.PlaceholderText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.WindowText, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.Button, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.ButtonText, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.Base, brush)
        brush = QBrush(QColor(0, 0, 0, 0))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.Window, brush)
        brush = QBrush(QColor(255, 255, 255, 128))
        brush.setStyle(Qt.NoBrush)
        palette.setBrush(QPalette.Disabled,  QPalette.PlaceholderText, brush)
        self.password.setPalette(palette)
        font = QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.password.setFont(font)
        self.password.setStyleSheet("font-size: 25px;\n"
                                    "letter-spacing: 1.5px;\n"
                                    "background: transparent;\n"
                                    "border:none;\n"
                                    "border-bottom: 1px solid grey;\n"
                                    "padding: 10px;\n"
                                    "color: white;")
        self.password.setEchoMode(QLineEdit.Password)
        self.password.setPlaceholderText("")
        self.password.setClearButtonEnabled(True)
        self.password.setObjectName("password")
        self.editPasswordButton = QPushButton(self.Pass)
        self.editPasswordButton.setGeometry(QRect(570, 40, 51, 41))
        self.editPasswordButton.setText("")
        self.editPasswordButton.setIcon(icon7)
        self.editPasswordButton.setFlat(True)
        self.editPasswordButton.setObjectName("editPasswordButton")
        self.AppName = QLabel(self.Body)
        self.AppName.setGeometry(QRect(10, 12, 211, 61))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.WindowText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.WindowText, brush)
        brush = QBrush(QColor(120, 120, 120))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.WindowText, brush)
        self.AppName.setPalette(palette)
        font = QFont()
        font.setFamily("Lucida Console")
        font.setPointSize(26)
        self.AppName.setFont(font)
        self.AppName.setObjectName("AppName")
        self.frame = QFrame(self.Body)
        self.frame.setGeometry(QRect(90, 250, 381, 411))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.frame.setObjectName("frame")
        self.UserFullName = QLabel(self.frame)
        self.UserFullName.setGeometry(QRect(10, 300, 381, 51))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.WindowText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.WindowText, brush)
        brush = QBrush(QColor(120, 120, 120))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.WindowText, brush)
        self.UserFullName.setPalette(palette)
        font = QFont()
        font.setFamily("Microsoft YaHei")
        font.setPointSize(20)
        font.setBold(True)
        self.UserFullName.setFont(font)
        self.UserFullName.setLayoutDirection(Qt.LeftToRight)
        self.UserFullName.setAlignment(Qt.AlignCenter)
        self.UserFullName.setObjectName("UserFullName")
        self.changePhotoButton = QPushButton(self.frame)
        self.changePhotoButton.setGeometry(QRect(100, 70, 201, 191))
        self.changePhotoButton.setStyleSheet("")
        self.changePhotoButton.setText("")
        icon8 = QIcon()
        icon8.addPixmap(QPixmap("contacts-512.png"),  QIcon.Normal,  QIcon.Off)
        self.changePhotoButton.setIcon(icon8)
        self.changePhotoButton.setIconSize(self.changePhotoButton.size())
        self.changePhotoButton.setCheckable(False)
        self.changePhotoButton.setAutoExclusive(True)
        self.changePhotoButton.setFlat(True)
        self.changePhotoButton.setObjectName("changePhotoButton")

        self.bioArea = QFrame(self.Body)
        self.bioArea.setGeometry(QRect(60, 670, 441, 191))
        self.bioArea.setFrameShape(QFrame.StyledPanel)
        self.bioArea.setFrameShadow(QFrame.Raised)
        self.bioArea.setObjectName("bioArea")
        self.bioContent = QLabel(self.bioArea)
        self.bioContent.setGeometry(QRect(0, 50, 441, 141))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.WindowText, brush)
        brush = QBrush(QColor(211, 211, 211, 25))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.Button, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.ButtonText, brush)
        brush = QBrush(QColor(211, 211, 211, 25))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.Base, brush)
        brush = QBrush(QColor(211, 211, 211, 25))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.Window, brush)
        brush = QBrush(QColor(255, 255, 255, 128))
        brush.setStyle(Qt.NoBrush)
        palette.setBrush(QPalette.Active,  QPalette.PlaceholderText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.WindowText, brush)
        brush = QBrush(QColor(211, 211, 211, 25))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.Button, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.ButtonText, brush)
        brush = QBrush(QColor(211, 211, 211, 25))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.Base, brush)
        brush = QBrush(QColor(211, 211, 211, 25))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.Window, brush)
        brush = QBrush(QColor(255, 255, 255, 128))
        brush.setStyle(Qt.NoBrush)
        palette.setBrush(QPalette.Inactive,  QPalette.PlaceholderText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.WindowText, brush)
        brush = QBrush(QColor(211, 211, 211, 25))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.Button, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.Text, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.ButtonText, brush)
        brush = QBrush(QColor(211, 211, 211, 25))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.Base, brush)
        brush = QBrush(QColor(211, 211, 211, 25))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.Window, brush)
        brush = QBrush(QColor(255, 255, 255, 128))
        brush.setStyle(Qt.NoBrush)
        palette.setBrush(QPalette.Disabled,  QPalette.PlaceholderText, brush)
        self.bioContent.setPalette(palette)
        font = QFont()
        font.setFamily("Lucida Handwriting")
        font.setPointSize(16)
        self.bioContent.setFont(font)
        self.bioContent.setStyleSheet(
            "background-color: rgba(211, 211,211, 0.1); border-radius: 18px;color: white;")
        self.bioContent.setTextFormat(Qt.AutoText)
        self.bioContent.setScaledContents(False)
        self.bioContent.setAlignment(Qt.AlignCenter)
        self.bioContent.setWordWrap(True)
        self.bioContent.setObjectName("bioContent")
        self.user_name = QLabel(self.bioArea)
        self.user_name.setGeometry(QRect(0, 0, 151, 51))
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active,  QPalette.WindowText, brush)
        brush = QBrush(QColor(255, 255, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Inactive,  QPalette.WindowText, brush)
        brush = QBrush(QColor(120, 120, 120))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled,  QPalette.WindowText, brush)
        self.user_name.setPalette(palette)
        font = QFont()
        font.setFamily("Swis721 Cn BT")
        font.setPointSize(16)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.user_name.setFont(font)
        self.user_name.setStyleSheet("padding: 10px;")
        self.user_name.setObjectName("user_name")

        self.horizontalLayout_3.addWidget(self.Body)
        self.verticalLayout.addWidget(self.mainBody)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.appName.setToolTip(_translate("MainWindow", "App Name"))
        self.appName.setText(_translate("MainWindow", "Chat Zone"))
        self.minimize.setToolTip(_translate("MainWindow", "Minimize"))
        self.restore.setToolTip(_translate("MainWindow", "Restore"))
        self.close.setToolTip(_translate("MainWindow", "Close"))
        self.appIcon.setToolTip(_translate("MainWindow", "Chat Zone"))
        self.Profile.setToolTip(_translate("MainWindow", "Profile"))
        self.messages.setToolTip(_translate("MainWindow", "Messages"))
        self.contacts.setToolTip(_translate("MainWindow", "Contacts"))
        self.settings.setToolTip(_translate("MainWindow", "Settings"))
        self.mode.setToolTip(_translate("MainWindow", "Light Mode"))
        self.refresh.setToolTip(_translate("MainWindow", "Refresh"))
        self.logout.setToolTip(_translate("MainWindow", "Logout"))
        self.usernameLabel.setText(_translate("MainWindow", "User Name"))
        self.username.setPlaceholderText(_translate("MainWindow", "_samar"))
        self.firstnameLabel.setText(_translate("MainWindow", "First Name"))
        self.firstName.setPlaceholderText(_translate("MainWindow", "Samar"))
        self.lastNameLabel.setText(_translate("MainWindow", "Last Name"))
        self.Lastname.setPlaceholderText(_translate("MainWindow", "Mahmoud"))
        self.bioLabel.setText(_translate("MainWindow", "Bio"))
        self.bio.setPlaceholderText(
            _translate("MainWindow", "Hey there, .... "))
        self.phoneNumber.setPlaceholderText(
            _translate("MainWindow", "01111111111"))
        self.phoneLabel.setText(_translate("MainWindow", "Phone Number"))
        self.PasswordLabel.setText(_translate("MainWindow", "Password"))
        self.AppName.setText(_translate("MainWindow", "ChatZone"))
        self.UserFullName.setText(_translate("MainWindow", "Samar Mahmoud"))
        self.bioContent.setText(_translate("MainWindow", "Hey, there....."))
        self.user_name.setText(_translate("MainWindow", "_samar"))
